### ISSUE TITLE
Add issue forms

### ISSUE THREAD

**Issue by eyllanesc** [cjolowicz/cookiecutter-hypermodern-python#1119] opened 2022-01-30 08:23 UTC
- https://github.com/tiangolo/typer/tree/master/.github/ISSUE_TEMPLATE
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by cjolowicz** [comment] 2022-02-09 09:20
Duplicate of #19 

Thanks for linking these useful resources! The typer issue template is entertaining for sure 😆

**Closed by cjolowicz** 2022-02-09 09:20 UTC
