### ISSUE TITLE
Option not to upload to PyPI and TestPyPI

### ISSUE THREAD

**Issue by gisandnes** [cjolowicz/cookiecutter-hypermodern-python#836] opened 2021-03-18 08:41 UTC
I would like to have the option not to upload to PYPI and TestPyPI. The user will then install the package from its GitHub repository. I need some of my packages to be private.

Whether to skip PYPI and TestPyPI could be another input parameter in cookiecutter.json.

I am working on my own fork to try to solve this: https://github.com/gisandnes/cookiecutter-hypermodern-python/blob/main/cookiecutter.json

**Comment by cjolowicz** [comment] 2021-04-15 15:03
Hi @gisandnes 

I'm afraid the situation with introducing an option for private packages is the same as in your issue about GH pages, see https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/835#issuecomment-820486428.

However, it would be sensible to skip PyPI and TestPyPI uploads if the repository has no secret variables with API tokens configured. IIUC that would solve your immediate use case, right? It would also resolve #440. Let me know if you can think of a way to achieve this. The other issue contains some information about why we could not figure this out back then.

**Comment by cjolowicz** [comment] 2021-11-22 12:03
Duplicate of #440

**Closed** 2021-11-22 12:03 UTC
Labels: ci
