### ISSUE TITLE
[Query] Dependency resolution failure across python versions

### ISSUE THREAD

**Issue by piyush-das** [cjolowicz/cookiecutter-hypermodern-python#515] opened 2020-08-19 04:59 UTC
## Issue
It appears that poetry's python specific package management doesn't translate properly to the export command Libraries for python3.6 are also getting exported which creating nox requirements for python3.7
### Steps to reproduce

```bash
cookiecutter gh:cjolowicz/cookiecutter-hypermodern-python  --checkout="2020.8.15"
# Accept defaults
cd hypermodern-python
# We would be supporting both 3.6 and 3.7
pyenv local 3.6.9 3.7.7
# Lets use 3.7 for testing
poetry env use 3.6
poetry install
# Lets add the problematic module
poetry add rich

# Nox tests on 3.6
nox -rs tests-3.6 # Completes correctly

# Nox tests on 3.7
nox -rs tests-3.7 # Generates error
```

We get the following error:
```log
ERROR: Could not find a version that satisfies the requirement dataclasses==0.7 (from -r .nox/tests-3-7/tmp/requirements.txt (line 10)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.7 (from -r .nox/tests-3-7/tmp/requirements.txt (line 10))
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/home/xyz/hypermodern-python/.nox/tests-3-7/bin/python -m pip install --upgrade pip' command.
```

The problem arrises due to dataclasses being exported in the requirements file for python3.7.
```ini
[[package]]
category = "main"
description = "A backport of the dataclasses module for Python 3.6"
name = "dataclasses"
optional = false
python-versions = ">=3.6, <3.7"
version = "0.7"
```

Even though  the lock mentions that dataclasses should be installed only for python 3.6, why is that it gets exported for 3.7 ? Please let me know if I am missing something.

Thanks

**Comment by cjolowicz** [comment] 2020-09-15 08:39
Thanks for the report.

I could reproduce this with the Poetry prerelease (1.1.0b2):

<details>
```Dockerfile
# docker build --build-arg PYTHON_VERSION=3.7 --build-arg POETRY_VERSION=1.1.0b2 .
ARG PYTHON_VERSION
FROM python:$PYTHON_VERSION
ARG POETRY_VERSION
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
ENV PATH $PATH:/root/.poetry/bin
RUN pip install cookiecutter
RUN cookiecutter gh:cjolowicz/cookiecutter-hypermodern-python  --checkout="2020.8.15" --no-input
WORKDIR hypermodern-python
RUN poetry add rich
RUN poetry export -f requirements.txt | grep dataclasses | grep python_version
<details/>

There is already an upstream issue for this: https://github.com/python-poetry/poetry/issues/2662

You can fix this by downgrading to the stable version of Poetry (1.0.10). (Beware however that the `env use` command in the stable version is broken: https://github.com/python-poetry/poetry/issues/2711)

I'm closing this because it is an upstream bug. Feel free to comment and continue the discussion.

**Closed by cjolowicz** 2020-09-15 08:39 UTC
